language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - lts/*
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "rohandamani.com.s3-us-west-1.amazonaws.com"
  skip_cleanup: true
